version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      -  echo Changing directory to Predictive-maintain-system...
      -  cd Predictive-maintain-system
      -  echo Installing dependencies...
      -  npm install
  build:
    commands:
      -  echo Changing directory to Predictive-maintain-system...
      -  ls
      -  cd Predictive-maintain-system
      -  echo Fetching environment variables...
      # Write .env directly inside the subdirectory
      -  cd Predictive-maintain-system
      -  echo "apiKey=$apiKey" > .env
      -  echo "authDomain=$authDomain" >> .env
      -  echo "projectId=$projectId" >> .env
      -  echo "storageBucket=$storageBucket" >> .env
      -  echo "messagingSenderId=$messagingSenderId" >> .env
      -  echo "appId=$appId" >> .env
      -  echo Build started...
      -  npm run build
      -  echo Build completed ==> Exporting artifacts...
artifacts:
  files:
    -  '**/*'
  discard-paths: no
  base-directory: Predictive-maintain-system/out